function(read_define config_path define_name output_name)
  file(READ "${config_path}" config_contents)
  string(REGEX MATCH "#define[ \t]+${define_name}[ \t]+\"([^\"]+)\"" define_match "${config_contents}")
  if(NOT define_match)
    message(FATAL_ERROR "${define_name} is missing from ${config_path}")
  endif()
  set(${output_name} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

function(verify_format_metadata plugin_root plugin_name bundle_domain bundle_manufacturer bundle_name format_name format_identifier)
  set(plist_path "${plugin_root}/resources/${plugin_name}-${format_name}-Info.plist")
  file(READ "${plist_path}" plist_contents)
  set(expected_identifier "${bundle_domain}.${bundle_manufacturer}.${format_identifier}.${bundle_name}")
  string(FIND "${plist_contents}" "<string>${expected_identifier}</string>" identifier_position)
  if(identifier_position EQUAL -1)
    message(FATAL_ERROR
      "Bundle identifier mismatch for ${plugin_name} ${format_name}: expected ${expected_identifier}")
  endif()
endfunction()

function(verify_plugin_metadata plugin_name)
  set(plugin_root "${PROJECT_ROOT}/plugins/${plugin_name}")
  set(config_path "${plugin_root}/config.h")
  read_define("${config_path}" "BUNDLE_DOMAIN" bundle_domain)
  read_define("${config_path}" "BUNDLE_MFR" bundle_manufacturer)
  read_define("${config_path}" "BUNDLE_NAME" bundle_name)

  verify_format_metadata("${plugin_root}" "${plugin_name}" "${bundle_domain}" "${bundle_manufacturer}" "${bundle_name}" "AU" "audiounit")
  verify_format_metadata("${plugin_root}" "${plugin_name}" "${bundle_domain}" "${bundle_manufacturer}" "${bundle_name}" "VST3" "vst3")
  verify_format_metadata("${plugin_root}" "${plugin_name}" "${bundle_domain}" "${bundle_manufacturer}" "${bundle_name}" "CLAP" "clap")
endfunction()

verify_plugin_metadata("Goodband")
verify_plugin_metadata("PitchTrails")
