if(BUILD_TESTING)
  add_custom_target(wfe-starter-checks)
  foreach(test_target wave_factory_dsp_tests goodband_character_preset_tests spirit_mirror_gesture_tests)
    if(TARGET ${test_target})
      add_dependencies(wfe-starter-checks ${test_target})
    endif()
  endforeach()
endif()
# Only manifest-bearing generated products are registered. Existing products stay explicit.
file(GLOB generated_manifests CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/plugins/generated/*/starter-manifest.json")
if(WFE_BUILD_PLUGINS)
  add_custom_target(wfe-generated-plugins)
endif()
foreach(manifest IN LISTS generated_manifests)
  get_filename_component(plugin_dir "${manifest}" DIRECTORY)
  get_filename_component(plugin_name "${plugin_dir}" NAME)
  add_subdirectory("${plugin_dir}" "plugins/generated/${plugin_name}")
endforeach()
